# Generated by Django 2.2.1 on 2019-05-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_goods_goodstype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccount', models.IntegerField(db_column='ccount')),
                ('goods', models.ForeignKey(db_column='goods_id', on_delete='CASCADE', to='index.Goods')),
                ('user', models.ForeignKey(db_column='user_id', on_delete='CASCADE', to='index.User')),
            ],
            options={
                'db_table': 'cart_info',
            },
        ),
    ]
